name: Custom Actions
description: Custom actions for bjia56s self-hosted runners
author: Brett Jia

inputs:
  action:
    description: The custom action to run
    required: true

runs:
  using: composite
  steps:
    - if: ${{ inputs.action == 'macppc-vm' }}
      uses: ./macppc-vm.yml