name: Test action
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  test_simple:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        action: macppc-vm